apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-frontend
  template:
    metadata:
      labels:
        app: python-frontend
    spec:
      containers:
        - name: python-frontend
          image: your-python-frontend-image:latest
          ports:
            - containerPort: 8501
